In [2]:
# !pip install numpy --- required only when nupy is not installed

In [1]:
# import numpy
import numpy as np

In [3]:
# create and ND array from python list
mylist = [1,2,3,4,5]

In [4]:
type(mylist)

list

In [5]:
# np.array() = which will convert given data into an array
my_arr = np.array(mylist)

In [6]:
my_arr

array([1, 2, 3, 4, 5])

In [7]:
mylist

[1, 2, 3, 4, 5]

In [8]:
type(my_arr)

numpy.ndarray

In [10]:
# array to list
type(list(my_arr))

list

In [11]:
# just for demo purpose / no need to attempt this code

In [12]:
import cv2

In [13]:
pic = cv2.imread('sample_img.jpeg')

In [14]:
pic

array([[[158, 138,  53],
        [159, 139,  54],
        [159, 139,  54],
        ...,
        [125,  67,  62],
        [128,  71,  62],
        [136,  79,  70]],

       [[159, 139,  54],
        [159, 139,  54],
        [160, 140,  55],
        ...,
        [114,  58,  53],
        [115,  60,  53],
        [122,  67,  60]],

       [[160, 139,  57],
        [161, 140,  58],
        [161, 140,  58],
        ...,
        [105,  50,  47],
        [103,  49,  42],
        [111,  57,  50]],

       ...,

       [[ 85,  79, 120],
        [ 84,  78, 119],
        [ 83,  77, 118],
        ...,
        [ 66,  70, 129],
        [ 68,  72, 131],
        [ 68,  72, 131]],

       [[ 98,  88, 124],
        [ 98,  88, 124],
        [ 97,  87, 123],
        ...,
        [ 65,  68, 129],
        [ 66,  69, 130],
        [ 66,  69, 130]],

       [[108,  94, 128],
        [108,  94, 128],
        [106,  92, 126],
        ...,
        [ 66,  67, 128],
        [ 66,  67, 128],
        [ 66,  67, 128]]

In [15]:
type(pic)

numpy.ndarray

In [16]:
pic.shape

(151, 270, 3)

# Numpy vs Python 

In [17]:
# speed # storage

In [18]:
# how much memory is consumed by single digit

num = 4

In [19]:
import sys

In [20]:
sys.getsizeof(num) , ' bytes'

(28, ' bytes')

In [ ]:
# so for 1000 intigers i need 28000 bytes

In [21]:
my_arr

array([1, 2, 3, 4, 5])

In [22]:
# itemsize : return size of single element in given array

In [24]:
my_arr.itemsize , ' bytes'

(8, ' bytes')

In [ ]:
# for 1000 intigers i am saving 20000

In [25]:
my_arr.nbytes , ' bytes'

(40, ' bytes')

In [26]:
28*5

140

In [27]:
import time

In [29]:
time.time()

1732355453.760103

In [30]:
time.time()

1732355454.293302

In [31]:
size = 1000000

l1 = range(size)   # 0,1,2.......
l2 = range(size)   # 0,1,2.......

ar1 = np.arange(size)
ar2 = np.arange(size)

start1 = time.time()
result1 = [x+y   for x,y in zip(l1,l2)]
stop1 = time.time()


print("Time Taken : ", (stop1-start1)*1000, 'ms')

Time Taken :  222.34106063842773 ms


In [32]:
size = 1000000

l1 = range(size)   # 0,1,2.......
l2 = range(size)   # 0,1,2.......

ar1 = np.arange(size)
ar2 = np.arange(size)

start2 = time.time()
result2 = ar1+ar2
stop2 = time.time()


print("Time Taken : ", (stop2-start2)*1000, 'ms')

Time Taken :  7.523775100708008 ms


# Numpy 

In [33]:
# creating 1D array

In [34]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [35]:
a[0]

1

In [36]:
a[1]

2

In [37]:
# creating 2D array

In [38]:
mylist = [[1,2,3],[4,5,6]]
b = np.array(mylist)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
# shape : returns no of rows and columns
b.shape

(2, 3)

In [40]:
# ndim : return number of dimesions

b.ndim

2

In [41]:
a.shape

(5,)

In [42]:
a.ndim

1

In [43]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
b[1]

array([4, 5, 6])

In [46]:
b[1][1]

5

In [47]:
data = np.array([7,9,2.4,'python'])
data

array(['7', '9', '2.4', 'python'], dtype='<U32')

In [48]:
data1 = np.array([7.1,9.8,2.4])
data1

array([7.1, 9.8, 2.4])

In [49]:
type(data)

numpy.ndarray

In [50]:
# creating 3 dimentional data

In [51]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
mylist = [
    [[1, 2, 3],[4, 5, 6]],
    [[11, 12, 13],[14, 15, 16]],
]
c = np.array(mylist)
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [14, 15, 16]]])

In [53]:
c.ndim

3

In [54]:
c.shape

(2, 2, 3)

In [55]:
mylist = [
    [[1, 2, 3],[4, 5, 6]],
    [[11, 12, 13],[14, 15, 16]],
    [[21, 22, 23],[24, 25, 26]],
    [[31, 32, 33],[34, 35, 36]],
]

d = np.array(mylist)
d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [14, 15, 16]],

       [[21, 22, 23],
        [24, 25, 26]],

       [[31, 32, 33],
        [34, 35, 36]]])

In [56]:
d.shape

(4, 2, 3)

In [57]:
d.ndim

3

In [58]:
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [14, 15, 16]]])

In [73]:
c.size

12

In [59]:
c[1]

array([[11, 12, 13],
       [14, 15, 16]])

In [60]:
c[1][0]

array([11, 12, 13])

In [61]:
c[1][0][1:]

array([12, 13])

In [62]:
# statestical operations on array

In [63]:
arr1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]],dtype = 'float')
arr1

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [64]:
arr1.shape

(3, 4)

In [65]:
print("Mean value is : ", arr1.mean())
print("MAx value is : ", arr1.max())
print("MIN value is : ", arr1.min())
print("Total value is : ", arr1.sum())

Mean value is :  6.5
MAx value is :  12.0
MIN value is :  1.0
Total value is :  78.0


In [66]:
arr1

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [67]:
arr1.ndim

2

In [68]:
x = np.array([[1,2],[3,4]])
y = np.array([[2,3],[4,5]])

In [69]:
x+y

array([[3, 5],
       [7, 9]])

In [70]:
x-y

array([[-1, -1],
       [-1, -1]])

In [71]:
x*y

array([[ 2,  6],
       [12, 20]])

In [72]:
x/y

array([[0.5       , 0.66666667],
       [0.75      , 0.8       ]])

In [76]:
# filtering an array

In [75]:
a

array([1, 2, 3, 4, 5])

In [77]:
a<4

array([ True,  True,  True, False, False])

In [78]:
a[a<4]

array([1, 2, 3])

In [79]:
arr_1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [80]:
arr_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [82]:
arr_1.ndim

1

In [83]:
arr_1.shape

(12,)

In [84]:
# convert single dim array to multi dim data : reshape

In [85]:
# 1,12
# 2,6
# 3,4
# 4,3
# 6,2
# 12,1

In [86]:
new_2d_arr = arr_1.reshape(3,4)
new_2d_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [88]:
new_2d_arr1 = arr_1.reshape(5,2)
new_2d_arr1

ValueError: cannot reshape array of size 12 into shape (5,2)

In [89]:
new_2d_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [90]:
# transpose

new_2d_arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [91]:
# 1D to 3D

In [92]:
new_3d_arr = arr_1.reshape(2,3,2)
new_3d_arr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [93]:
arr_1.reshape(1,12,1)

array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12]]])

In [94]:
# converting 3D, 2D to 1D

In [96]:
new_3d_arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [97]:
new_2d_arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [99]:
new_3d_arr.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [98]:
# trignometric

In [100]:
np.sin(np.pi)

1.2246467991473532e-16

In [101]:
np.cos(np.pi)

-1.0

In [102]:
np.cos(np.pi/2)

6.123233995736766e-17

In [104]:
data = np.array([[1,3],[2,4]])

for x in data.flat:
    print(x)

1
3
2
4


In [105]:
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [14, 15, 16]]])

In [108]:
c.shape

(2, 2, 3)

In [106]:
c.T

array([[[ 1, 11],
        [ 4, 14]],

       [[ 2, 12],
        [ 5, 15]],

       [[ 3, 13],
        [ 6, 16]]])

In [107]:
c.T.shape

(3, 2, 2)

In [109]:
# ones : generate array of ones

np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [110]:
# zeros : generate array of zeros

np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [111]:
data = np.array([1.2,7.9,3.6,9.9])

In [112]:
# ceil() : return ceil value of element

np.ceil(data)

array([ 2.,  8.,  4., 10.])

In [113]:
# floor() : return floor value of element

np.floor(data)

array([1., 7., 3., 9.])

In [114]:
np.round(4.57595959,3)

4.576

In [ ]:
# array stacking 

In [117]:
x = np.array([1,2])
y = np.array([4,5])

In [119]:
np.hstack((x,y))

array([1, 2, 4, 5])

In [120]:
np.vstack((x,y))

array([[1, 2],
       [4, 5]])